14-rials-associations/mod_name_gen/config/routes.rb
Rails.application.routes.draw do
  resources :votes, only: [:new, :create]
  resources :users, only: [:show, :index]
  resources :suggestions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

14-rials-associations/mod_name_gen/app/models/suggestion.rb
class Suggestion < ApplicationRecord
  has_many :votes 
  has_many :users, through: :votes
end

14-rials-associations/mod_name_gen/app/models/user.rb
class User < ApplicationRecord
  has_many :votes 
  has_many :suggestions, through: :votes
end

14-rials-associations/mod_name_gen/app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :find_suggestion, only: [:show, :update, :edit, :destroy]

  def index
    @suggestions = Suggestion.all
    # render :index
  end 
  
  # def show
    # @suggestion = Suggestion.find(params[:id]) # BEFORE ACTION
  # end 

  def new 
    @suggestion = Suggestion.new
    # render :new
  end 

  def create  
    suggestion = Suggestion.create(suggestion_params)

    redirect_to suggestion_path(suggestion)
  end 

  # def edit 
  #   # @suggestion = Suggestion.find(params[:id]) # BEFORE ACTION
  #   # render :edit
  # end 

  def update 
    # @suggestion = Suggestion.find(params[:id]) # BEFORE ACTION
    @suggestion.update(suggestion_params)

    redirect_to suggestion_path(@suggestion)
  end 

  def destroy
    # @suggestion = Suggestion.find(params[:id])
    @suggestion.destroy

    redirect_to suggestions_path
  end 

  private 

  def suggestion_params
    params.require(:suggestion).permit(:name, :slogan, :img_url)
  end

  def find_suggestion
    @suggestion = Suggestion.find(params[:id])
  end
end

14-rials-associations/mod_name_gen/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all
  end 

  def show 
    @user = User.find(params[:id])
  end 

end

14-rials-associations/mod_name_gen/app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new  
    @vote = Vote.new
    @suggestions = Suggestion.all
    @users = User.all

    render :new
  end 

  def create   
    vote = Vote.create(vote_params)
    # vote = Vote.new(params)
    # vote.save
    redirect_to suggestion_path(vote.suggestion_id)
  end 

  private 

  def vote_params
    params.require(:vote).permit(:suggestion_id, :user_id)
  end 
end

14-rials-associations/mod_name_gen/app/views/suggestions/edit.html.erb
<h3>Edit Suggestion</h3>

<%# <form action='/suggestions' method='POST'>
  <input type="text" name="suggestion[name]"> 
</form> %>

<%= form_for @suggestion do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :slogan %>
  <%= f.text_field :slogan %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit %>
<% end %>

14-rials-associations/mod_name_gen/app/views/suggestions/index.html.erb
<h3>Suggestion List</h3>


<div class="index-container">
  <% @suggestions.each do |suggestion| %>
    <div class='index-item'>
      <img class='index-img' src="<%=suggestion.img_url%>" alt="<%=suggestion.name%>"> 
      <h6>Name: <%= link_to suggestion.name, suggestion %></h6> 
    </div>
  <% end %>
</div>

14-rials-associations/mod_name_gen/app/views/suggestions/new.html.erb
<h3>Create New Suggestion</h3>

<%# <form action='/suggestions' method='POST'>
  <input type="text" name="suggestion[name]"> 
</form> %>

<%= form_for @suggestion do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :slogan %>
  <%= f.text_field :slogan %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit %>
<% end %>

14-rials-associations/mod_name_gen/app/views/users/index.html.erb
<h3>User List</h3>


<div class="index-container">
  <% @users.each do |user| %>
    <div class='index-item'>
      <img class='index-img' src="<%=user.img_url%>" alt="<%=user.name%>"> 
      <h6>Name: <%= link_to user.name, user_path(user) %></h6> 
    </div>
  <% end %>
</div>

14-rials-associations/mod_name_gen/app/views/users/show.html.erb
<h3>User Show Page</h3>

<h5>Name: <%= @user.name %></h5>
<marquee><img src="<%= @user.img_url %>" alt="<%= @user.img_url%> "></marquee>
<br>
<hr>
<h3>I have voted for...</h3>
<ul>
<% @user.votes.uniq.each do |vote| %>
  <li><%= vote.suggestion.name %></li>
<% end %>
</ul>
<br>
<hr>
<%= link_to "Back to List", users_path %>

14-rials-associations/mod_name_gen/app/views/votes/new.html.erb
<h3>Vote For a Suggestion</h3>

<%= form_for @vote do |f| %>
  <%= f.label :user_id %>
  <%= f.collection_select :user_id, @users, :id, :name %>

  <%= f.label :suggestion_id %>
  <%= f.collection_select :suggestion_id, @suggestions, :id, :name %>

  <%= f.submit %>
<% end %>