13-rails-CRUD/mod-name-picker/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :suggestions, only: [:index, :show, :new, :create, :edit, :update]

  
  
  
  #HTTP Verb   |     URL   |   contorller & action  | Route Helper

  # get '/suggestions', to: 'suggestions#index', as: 'suggestions'
  # get '/suggestions/:id', to: 'suggestions#show', as: 'suggestion'
  
  # get '/suggestions/new', to: 'suggestions#new', as: 'new_suggestion'
  # post '/suggestions', to: 'suggestions#create'
  
  # get '/suggestions/:id/edit', to: 'suggestions#edit'
  # patch '/suggestions/:id', to: 'suggestions#update'
  
  # delete '/suggestions/:id', to: 'suggestions#delete'
  
end

13-rails-CRUD/mod-name-picker/app/models/suggestion.rb
class Suggestion < ApplicationRecord
end

13-rails-CRUD/mod-name-picker/app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :find_suggestion, only: [:show, :update, :edit, :delete]

  def index
    @suggestions = Suggestion.all
    # render :index
  end 
  
  # def show
  # end 

  def new 
    @suggestion = Suggestion.new
    # render :new
  end 

  def create  
    suggestion = Suggestion.create(suggestion_params)

    redirect_to suggestion_path(suggestion)
  end 

  def edit 
    # @suggestion = Suggestion.find(params[:id])
    # render :edit
  end 

  def update 
    # suggestion = Suggestion.find(params[:id])
    @suggestion.update(suggestion_params)

    redirect_to suggestion_path(@suggestion)
  end 

  def delete 
    # @suggestion = Suggestion.find(params[:id])
  end 

  private 

  def suggestion_params
    params.require(:suggestion).permit(:name, :slogan, :img_url)
  end

  def find_suggestion
    @suggestion = Suggestion.find(params[:id])
  end
  

end

13-rails-CRUD/mod-name-picker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModNamePicker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><marquee>Mod Name Picker!!!</marquee></h1>
    <%= yield %>
  </body>
</html>

13-rails-CRUD/mod-name-picker/app/views/suggestions/index.html.erb
<h3>Suggestion List</h3>

<ul> 
  <% @suggestions.each do |suggestion|%>
    <li><%= link_to suggestion.name, suggestion_path(suggestion) %></li>
  <% end%>
</ul>

13-rails-CRUD/mod-name-picker/app/views/suggestions/show.html.erb
<h3>Suggestion Show Page</h3>

<h5><%= @suggestion.name %></h5>
<h5><%= @suggestion.slogan %></h5>

<br>
<hr>
<%= link_to "Back to List", suggestions_path %>